apiVersion: v1
kind: ConfigMap
metadata:
  name: earnings-intel-task-dispatcher-config
  namespace: tmic
data:
  workflow.env: |
    APP_MODE=task_dispatcher
    EVENT_CALENDAR_DISPATCH_WINDOW_MINUTES=10
